### ISSUE TITLE
fastafunk add_columns

### ISSUE THREAD

**Issue by yaotli** [GECO-PH/grapevine-anywhere#2]
I believe `fastafunk add_columns` function needs  `--new-columns` point to the column names of the input data. In rules 5/add_country_lineage_to_redcap_metadata and 5/update_lineage_metadata, both involve output/5/updated_traits.csv which contains only {country}_lineage but not {country}_cluster, so I think we need additional `--where-column` for both cases. 

I am thinking - 
add `--where-column {params.country_code}_cluster={params.country_code}_lineage` here, and 
https://github.com/GECO-PH/grapevine-anywhere/blob/7967de62ebbeea00a78bf8bb32b587e63fda0b58/rules/5_define_redcap_lineages_and_cut_out_trees.smk#L367

 `--where-column {params.country_code}_cluster={params.country_code}_lineage microreact_lineage=microreact_lineage` here.

https://github.com/GECO-PH/grapevine-anywhere/blob/7967de62ebbeea00a78bf8bb32b587e63fda0b58/rules/5_define_redcap_lineages_and_cut_out_trees.smk#L118

**Comment by TriassicSalamander** [comment]
Thanks for pointing this out. I've implemented these changes.
